name: Instagram Username Checker

on:
  workflow_dispatch:

jobs:
  check-usernames:
    runs-on: ubuntu-latest

    steps:
      - name: Repositoriyani yuklab olish
        uses: actions/checkout@v4

      - name: Python o'rnatish
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Kutubxonalarni o'rnatish
        run: |
          pip install requests

      - name: Tekshiruv dasturini ishga tushirish
        run: |
          python checker.py

      - name: Natijalarni Artifact sifatida saqlash
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: instagram-natijalar
          path: |
            results.txt
            possible.txt
